# Generated by Django 2.2.2 on 2019-07-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libo', '0002_auto_20190627_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'get_latest_by': 'name', 'ordering': ['name', 'surname'], 'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='lendperiods',
            options={'get_latest_by': 'days_amount', 'ordering': ['days_amount'], 'verbose_name': 'Lending period', 'verbose_name_plural': 'Lending periods'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'get_latest_by': 'name', 'ordering': ['name'], 'verbose_name': 'Publisher', 'verbose_name_plural': 'Publishers'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'get_latest_by': 'creation_date', 'ordering': ['review'], 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'get_latest_by': 'join_date', 'ordering': ['user'], 'verbose_name': 'User profile', 'verbose_name_plural': 'User profiles'},
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
